### ISSUE TITLE
development

### ISSUE THREAD

**Issue by Butonix** [DIma-Kush/Social-network#87]
Hello!
Excuse me, will the project develop?
Are there any plans to add music and video as in vk

**Comment by dmytro-kushnir** [comment]
Hello!
yes , it's under develop now
music and video are in our develop plan for now.

чт, 21 сент. 2017 г. в 8:40, Butonix <notifications@github.com>:

**Comment by Butonix** [comment]
Good.
Another would be to make a search, like in Vk by country and city, by age, on the site or not, with or without photo, sex.
now you can not write comments to the photo, you can not do husky

**Comment by dmytro-kushnir** [comment]
ok,thanks for your recommendation :-)


чт, 21 сент. 2017 г. в 9:18, Butonix <notifications@github.com>:

**Comment by Butonix** [comment]
Please, look your email
